name = "browser-rendering-api"
main = "puppeteer-worker.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[browser]
binding = "browser"

[[kv_namespaces]]
binding = "SCREENSHOTS"
id = "1c2c4dce1e394684b0ecbff7424b4975"
